# Создание 3D карты Днепропетровска!
 
#### 0. Если у вас есть данные о высотах зданий все делается очень просто:

добавляем в стили название слоя с параметрами
```css
#3D-building{
  building-fill: #444;
  building-height: "[height]";
}
```
на выходе получаем [псевдо-3Dкарту](https://a.tiles.mapbox.com/v4/andygol.m044di7c/page.html?access_token=pk.eyJ1IjoiYW5keWdvbCIsImEiOiJwSUo1SV9ZIn0.5Y4I6L-HlwNhbMMSzhU0Mg#15/48.4701/35.0398).

<iframe width='100%' height='500px' frameBorder='0' src='https://a.tiles.mapbox.com/v4/andygol.m044di7c/attribution,zoompan,zoomwheel,geocoder,share.html?access_token=pk.eyJ1IjoiYW5keWdvbCIsImEiOiJwSUo1SV9ZIn0.5Y4I6L-HlwNhbMMSzhU0Mg'></iframe>

#### Теперь подробно.

ОСМ – 2-мерная карта. То есть, карта плоская, без учета неровностей рельефа. Все что находится на поверхности, по-умолчанию, принимается как `layer=0` (поверхность рек - также), то что над поверхностью – `layer=1` и т.д. (мосты, эстакады и прочее), то что под землей (водой) – `layer=-1` и т.д. (туннели, подземные сооружения). Но, несмотря на всю эту двумерность мы можем оперировать третьим измерением, указывая высоту зданий, деревьев, оград и препятствий; глубину водоёмов и тому подобное.

В итоге, мы получаем приближенную к реальному (без учета особенностей рельефа) картину окружающего нас мира.

## 1. Получение данных
 
Для того чтобы создать 3D карту нам необходимо получить данные, на основе которых мы будем создавать нашу карту. Для этого у объектов должны быть указаны данные об их высоте. В Днепропетровске с указанием высоты/этажности зданий дела обстоят, можно сказать, не плохо. По крайней мере, большинство зданий в центральной части города и в местах многоэтажной застройки имеют информацию о количестве этажей и/или указана их высота. 
	
Для получения данных я воспользовался запросом к серверу [overpass-turbo.eu](http://overpass-turbo.eu). Чтобы не писать запрос вручную воспользуемся встроенным помощником:

![overpass_helper](https://cloud.githubusercontent.com/assets/369696/7304052/531d8924-e9fd-11e4-9006-f6883924f103.png)

В результате у нас будет сформирован запрос: 
```
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“building in Dnipropetrovsk”
*/
[out:json][timeout:25];
// fetch area “Dnipropetrovsk” to search in
{{geocodeArea:Dnipropetrovsk}}->.searchArea;
// gather results
(
  // query part for: “building”
  way["building"](area.searchArea);
  relation["building"](area.searchArea);
);
// print results
out body;
>;
out skel qt;
```
Но давайте не будем спешить и отменим его автоматическое выполнение, так как нам нужно его немного дополнить. Добавим параметры для получения данных о домах обозначенных тегами `building:part`

```
way["building:part"](area.searchArea);
relation["building:part"](area.searchArea);
```

а также увеличим параметр `[timeout:*]` (время ожидания выполнения запроса) с 25 до 500 секунд. Вот теперь пробуем выполнить [наш запрос](http://overpass-turbo.eu/s/8XX) в браузере. Сразу хочу предупредить, если у вас объем оперативной памяти менее 8 Гб ваш браузер скорее всего не сможет обработать полученные данные. Как выйти из этой ситуации? Все просто – воспользоваться “Экспортом”. Экспортировать будем сразу в JOSM

![overpass_export](https://cloud.githubusercontent.com/assets/369696/7304095/a0d82084-e9fd-11e4-9f4d-697bac4f48b8.png)

Для этого у вас должен быть открыт JOSM с включенным “Дистанционным управлением”. 

![overpass_export_fix](https://cloud.githubusercontent.com/assets/369696/7304123/cef965e0-e9fd-11e4-83e6-e94d33a2b97b.png)

Помощник предложит вам исправить запрос таким образом, чтобы данные были получены в формате XML, именно с ними и работает JOSM. Нажимайте на кнопку “Исправить запрос” и переключайтесь в JOSM. После загрузки данных их можно сохранить в файл (*.osm)

![josm_with_data](https://cloud.githubusercontent.com/assets/369696/7304148/fc5a3974-e9fd-11e4-920c-1b1bcf692c12.png)

## 2. Установка SQL-сервера

Для хранения данных в БД будем использовать [PostgreSQL](http://wiki.openstreetmap.org/wiki/PostgreSQL) вместе с [PostGIS](http://wiki.openstreetmap.org/wiki/PostGIS)
Инструкции по установке сервера и инициализации БД находятся [здесь](http://wiki.openstreetmap.org/wiki/PostGIS/Installation), следуйте инструкциям для вашей ОС.

[Запускаем сервер](http://www.postgresql.org/docs/9.4/static/server-start.html) командой  
`$ postgres -D /usr/local/pgsql/data`

в моем случае  
`andygol$ postgres -D /usr/local/var/postgres`

[активируем PostGIS](http://postgis.net/docs/postgis_installation.html#install_short_version)  
`andygol$ psql gisdb`
`gisdb=# CREATE EXTENSION postgis;`  
или  
`andygol$ psql -d gisdb -c 'CREATE EXTENSION postgis;'`

## 3. Экспорт данных в БД

Для экспорта данных воспользуемся [osm2pgsql](http://wiki.openstreetmap.org/wiki/Osm2pgsql)

выполним команду:  
`osm2pgsql -s -S ~/Documents/Mapbox/Studio/3dp/dp-default.style -d gisdb -C 4000 --number-processes 2 dp-buildings.osm`

Обратите внимание на параметр  
`-S ~/Documents/Mapbox/Studio/3dp/dp-default.style`

он указывает на размещение файла с указанием полей которые будут использоваться для импорта даных в БД. Так как в стандартном файле указаны не все необходимые поля добавим их в наш файл:
```
  node,way   building:part text        polygon #add for 3d
  node.way   building:levels text      polygon #add for 3d
  node,way   building:height text      polygon #add for 3d
  node,way   building:min_level text   polygon #add for 3d
  node,way   height       text         polygon #add for 3d
  node,way   min_height   text         polygon #add for 3d
```
http://wiki.openstreetmap.org/wiki/Osm2pgsql#Import_style

## 4. Проверка данных в JOSM

Перед тем как заливать данные в БД их необходимо проверить. Воспользуемся для этого Валидатором. Могу сказать, что мне пришлось потратить несколько часов на устранение ошибок и внесение исправлений и уточнений в данные – http://www.openstreetmap.org/changeset/30387512

Ну, что ж если вы экспортировали данные до того как их проверили вам прийдется сделать это еще раз :)

## 5. Повторный экспорт

Все что нам нужно это повторить п.3  
`osm2pgsql -с —s -S ~/Documents/Mapbox/Studio/3dp/dp-default.style -d gisdb -C 4000 --number-processes 2 dp-buildings.osm`

можно добавить ключ `-с`, для удаления существующих данных в БД

## 6. Создание SQL-запросов

Основным параметром для построения нашей 3D карты являются данные о высоте зданий, тег `height`. Но как оказывается очень малое количество зданий имеют данные о высоте. Однако, у нас есть данные об этажности некоторых зданий, тег `building:levels`.  Воспользуемся ими:
``` sql
SELECT way, height
FROM planet_osm_polygon
WHERE ((height IS NOT NULL) AND ("building:levels" IS NOT NULL)) 
 /*дома у которых есть высота и этажность*/
ORDER BY ST_YMax(ST_Envelope(way))
```
```sql
SELECT way, height
FROM planet_osm_polygon
WHERE ((height IS NOT NULL) AND ("building:levels" IS NULL)) 
 /*дома у которых есть высоты но нет этажности*/
ORDER BY ST_YMax(ST_Envelope(way))
```
```sql
SELECT way, (CAST ("building:levels" AS int) * 3 + 3) as height
FROM planet_osm_polygon
WHERE ((height IS NULL) AND ("building:levels" IS NOT NULL)) 
/*дома у которых нет высоты но есть этажность*/
ORDER BY ST_YMax(ST_Envelope(way))
```
и наконец дома, у которых нет данных о высоте и о количестве этажей
```sql
SELECT way, 4.5 AS height
FROM planet_osm_polygon
WHERE (height IS NULL AND "building:levels" IS NULL)
ORDER BY ST_YMax(ST_Envelope(way))
```
## 7. Получение данных для их стилизации в Mapbox Studio

“Теперь попробуем со всем этим взлететь”
Запускаем [Mapbox Studio](https://www.mapbox.com/mapbox-studio/#darwin)

Создаем новый проект, добавляем слой с данными:

![add_data_layer](http://i.imgur.com/NQ0m3NO.gif)

Чтобы у вас не появлялось сообщение об ошибке, на вкладке SQL нужно добавить сам запрос. 

![mbs_sql_quary](https://cloud.githubusercontent.com/assets/369696/7304586/1a6c0a70-ea01-11e4-80c2-d60099c634d5.png)

повторяем для каждого запроса, в итоге у нас получится 4 слоя. 
Также дополнительно советую почитать – https://www.mapbox.com/guides/postgis-manual/#sql-queries

![mbs_data_source](https://cloud.githubusercontent.com/assets/369696/7304620/49c84842-ea01-11e4-8bcd-f43145f339b5.png)

Сохраним и отправим данные на сервер Mapbox.

Теперь нам нужно создать стиль для отображения данных

![mbs_data_styling](http://i.imgur.com/il4Mjw9.gif)

Как я писал в самом начале, для того чтобы у нас получились 3-х мерные домики, нам нужно воспользоваться свойством `building-height`: «высота в метрах».

```css
#data_h_l {
  building-height: [height] ; 
  building-fill: #0068c2;
  building-fill-opacity: 0.4;
  }

#data_h_wo_l {
  building-height: [height] ; 
  building-fill: #16ccdd;
  building-fill-opacity: 0.4;
  }

#data_wo_h_l {
  building-height: [height] ; 
  building-fill: #0f804b;
  building-fill-opacity: 0.4;
  }

#data_wo_hl {
  building-height: [height] ; 
  building-fill: #7e7e7e;
  building-fill-opacity: 0.4;
  }
```
Теперь сохраняем и загружаем стиль на сервер Mapbox

![mbs_upload_style](https://cloud.githubusercontent.com/assets/369696/7304723/d56de140-ea01-11e4-9d59-b1b88d9e79cb.png)

Также о работе с Mapbox Studio читаем здесь – https://www.mapbox.com/help/studio-common-questions/

## 8. Публикация карты в онлайн 

Для создания карты будем использовать [Mapbox Editor](https://www.mapbox.com/editor/). Внимательно читаем и смотрим на изображения, что бы у вас получилось также.
https://www.mapbox.com/help/adding-custom-layers/

В итоге, у вас должно получиться так как у меня

![mbe_project](https://cloud.githubusercontent.com/assets/369696/7304793/2dc531c2-ea02-11e4-87b3-679f5e547f25.png)

Для того, чтобы опубликовать вашу карту для широкой общественности снимите флажок, как на рисунке ниже
 
![mbe_public](https://cloud.githubusercontent.com/assets/369696/7304830/6d3ccf2c-ea02-11e4-88ae-4c2833557056.png)

Если у вас есть еще вопросы о Mapbox Online Editor – https://www.mapbox.com/help/#editor

##### Что еще можно почитать:
https://switch2osm.org/?s=osm2pg
http://learnosm.org/en/map-design/
http://learnosm.org/en/osm-data/
